# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['learn', 'image', 'label', 'examples', 'intf', 'classify_image']

# %% ../app.ipynb 2
from fastai.vision.all import *
import gradio as gr

# %% ../app.ipynb 6
learn = load_learner('export.pkl')

# %% ../app.ipynb 12
def classify_image(img):
    pred,pred_idx,probs = learn.predict(img)
    return dict(zip(learn.dls.vocab, map(float, probs)))

# %% ../app.ipynb 17
image = gr.components.Image(shape=(192,192))
label = gr.components.Label()
examples = ['cat.jpg', 'dog.jpg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
